version: '3.7'

volumes:
    kong_data: {}
    konga_data: {}

networks:
    kong-net:
        driver: bridge

services:
    kong-database:
        image: postgres:12.1
        environment:
            POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
            POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
            POSTGRES_USER: ${KONG_PG_USER:-kong}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
            interval: 5s
            timeout: 5s
            retries: 5
        stdin_open: true
        tty: true
        networks:
            - kong-net
        volumes:
            - kong_data:/var/lib/postgres/data

    kong:
        build:
            context: .
        user: ${KONG_USER:-root}
        networks:
            - kong-net
        restart: on-failure
        ports:
            - "${KONG_PG_LISTEN}:${KONG_PG_LISTEN}/tcp"
            - "${KONG_ADMIN_PG_LISTEN}:${KONG_ADMIN_PG_LISTEN}/tcp"
            - "${KONG_PG_LISTEN_SSL}:${KONG_PG_LISTEN_SSL}/tcp"
            - "${KONG_ADMIN_PG_LISTEN_SSL}:${KONG_ADMIN_PG_LISTEN_SSL}/tcp"
        environment:
            KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
            KONG_PG_HOST: ${KONG_PG_HOST:-kong-database}
            KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
            KONG_PG_USER: ${KONG_PG_USER:-kong}
            KONG_PROXY_ERROR_LOG: /dev/stdout
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_LOG_LEVEL: info
            KONG_PROXY_LISTEN: 0.0.0.0:${KONG_PG_LISTEN}
            KONG_ADMIN_LISTEN: 0.0.0.0:${KONG_ADMIN_PG_LISTEN}
        depends_on:
            - kong-database
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 30s
            timeout: 10s
            retries: 5
   
    konga-prepare:
        image: pantsel/konga:next
        command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
        networks:
            - kong-net
        restart: on-failure
        links:
            - kong-database
        depends_on:
            - kong-database
    
    konga:
        image: pantsel/konga:next
        restart: on-failure
        networks:
            - kong-net
        environment:
            DB_ADAPTER: postgres
            DB_DATABASE: ${KONG_PG_DATABASE:-kong}
            DB_HOST: ${KONG_PG_HOST:-kong-database}
            DB_USER: ${KONG_PG_USER:-kong}
            DB_PASSWORD: ${KONG_PG_PASSWORD:-kong}
            TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
            DB_DATABASE: konga_db
            KONGA_HOOK_TIMEOUT: 120000
            NODE_ENV: production
        depends_on:
            - kong-database
        ports:
            - 1337:1337